# HTTP → HTTPS 리다이렉트
server {
    listen 80;
    return 301 https://$host$request_uri;
}

# HTTPS 메인 서버
server {
    listen 443 ssl;
    client_max_body_size 20M;

    ssl_certificate     /etc/letsencrypt/live/3-36-101-246.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/3-36-101-246.sslip.io/privkey.pem;

    include /etc/nginx/mime.types;
    types {
        application/wasm wasm;
    }
    
    # 소셜 로그인 콜백
    location /auth/ {
        proxy_pass http://backend:8000/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }

    #
    location ~ ^/(users|chats|upload|keywords|analysis|wishlist|qna)(/|$) {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }
    location = /skin-mbti {
        proxy_pass http://backend:8000;
    }
    location ~ ^/skin-mbti/(shared|share|[0-9]+)(/|$) {
        proxy_pass http://backend:8000;
    }

    # 프론트엔드 (반드시 마지막에)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

}